Description: >
  This template deploys an Application Load Balancer that exposes our ECS services.

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    AllowedValues:
      - Prod
      - Stage
      - Dev
      - Test

  ResourceName:
    Description: Provide the resource type or service name being managed by this stack.
    Type: String
    Default: ECS
    AllowedValues:
      - ECS
      - EC2

  VPC:
    Description: Choose which VPC the Applicaion Load Balancer should be deployed to
    Type: AWS::EC2::VPC::Id

  Subnets:
    Description: Choose which subnets the Applicaion Load Balancer should be deployed to
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroup:
    Description: Select the Security Group to apply to the Applicaion Load Balancer
    #Type: AWS::EC2::SecurityGroup::Id
    Type: String
    AllowedValues:
      - TestECSLoadBalancerSG-SecurityGroupID

Resources:

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref EnvironmentName
      Subnets: !Ref Subnets
      SecurityGroups: 
        #- !Ref SecurityGroup
        - Fn::ImportValue: !Sub TestECSLoadBalancerSG-SecurityGroupID
      Tags: 
        - Key: Name
          Value: !Ref EnvironmentName

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup
    
  # We define a default target group here, as this is a mandatory Parameters
  # when creating an Application Load Balancer Listener. This is not used, instead
  # a target group is created per-service in each service template (../services/*)
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: default
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
           
Outputs:

  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref LoadBalancer

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub "${EnvironmentName}${ResourceName}-LoadBalancerUrl"

  Listener:
    Description: A reference to a port 80 listener
    Value: !Ref LoadBalancerListener  

